word_embeddings:
  # Two types of word embedding algorithm (word2vec and glove) are supported.
  # Just set the default to empty string to disable the word embeddings
  default: word2vec_pos
  word2vec:
#    path: data/GoogleNews-vectors-negative300.bin
    path: ../data/simplified_model_word2vec_format400
    dimension: 400
    binary: False
  word2vec_pos:
#    path: data/GoogleNews-vectors-negative300.bin
    path: ../data/simplified_pos_model_word2vec_format200
    dimension: 200
    binary: False
  glove:
    path: ../data/glove.6B.100d.txt
    dimension: 100
    length: 400000

char_embeddings:
  # Two types of word embedding algorithm (word2vec and glove) are supported.
  # Just set the default to empty string to disable the word embeddings
  default: word2vec
  word2vec:
#    path: data/GoogleNews-vectors-negative300.bin
    path: ../data/simplified_model_char2vec_format200
    dimension: 200
    binary: False

datasets:
  # Support currently 3 datasets: mrpolarity, 20newsgroup and localdata
  default: concept5
  mrpolarity:
    positive_data_file:
      path: "../data/rt-polaritydata/rt-polarity.pos"
      info: "Data source for the positive data"
    negative_data_file:
      path: "../data/rt-polaritydata/rt-polarity.neg"
      info: "Data source for the negative data"
  20newsgroup:
    # The dataset includes following 20 newsgroups:
    # alt.atheism, comp.windows.x, rec.sport.hockey, soc.religion.christian
    # comp.graphics, misc.forsale, sci.crypt, talk.politics.guns
    # comp.os.ms-windows.misc, rec.autos, sci.electronics, talk.politics.mideast
    # comp.sys.ibm.pc.hardware, rec.motorcycles, sci.med, talk.politics.misc
    # comp.sys.mac.hardware, rec.sport.baseball, sci.space, talk.religion.misc
    categories:
      - alt.atheism
      - comp.graphics
      - sci.med
      - soc.religion.christian
    shuffle: True
    random_state: 42
  concept5:
    training_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/train"
      info: "Data source for the training data"
    target_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/train_target"
      info: "Data source for the target data"
    pos_training_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/train_pos"
      info: "Data source for the training data with POS tags"
    pos_target_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/train_target"
      info: "Data source for the target data"
  concept5_test:
    training_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/test"
      info: "Data source for the training data"
    target_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/test_target"
      info: "Data source for the target data"
    pos_training_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/test_pos"
      info: "Data source for the training data with POS tags"
    pos_target_data_file:
      path: "../data/chinese-relation_extraction/experiment_data_dbrcnn_pos/test_target"
      info: "Data source for the target data"
  localdata:
    # Load text files with categories as subfolder names.
    # Individual samples are assumed to be files stored
    # a two levels folder structure such as the following:
    # container_folder/
    #   category_1_folder/
    #     file_1.txt file_2.txt ... file_42.txt
    #   category_2_folder/
    #     file_43.txt file_44.txt ...
    #
    # As an example, a SentenceCorpus dataset from
    # https://archive.ics.uci.edu/ml/datasets/Sentence+Classification
    # has been used. The dataset includes following 3 domains:
    # arxiv, jdm and plos
    container_path: ../data/SentenceCorpus
    categories:
    shuffle: True
    random_state: 42

